updated workflow

diff --git a/.github/workflows/gitops-ci.yml b/.github/workflows/gitops-ci.yml
--- a/.github/workflows/gitops-ci.yml
+++ b/.github/workflows/gitops-ci.yml
@@ -9,6 +9,10 @@ on:
       - 'Dockerfile'
   workflow_dispatch:
 
+concurrency:
+  group: bankapp-ci
+  cancel-in-progress: true
+
 permissions:
   contents: write
 
@@ -17,12 +21,15 @@ env:
 
 jobs:
   build-and-push:
+    if: github.actor != 'github-actions[bot]'
     name: Build, Test & Push Docker Image
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -74,7 +81,16 @@ jobs:
           git add k8s/bankapp-deployment.yml
 
           if ! git diff --cached --quiet; then
-            git commit -m "ci: update bankapp image to ${{ steps.tag.outputs.sha_short }} [skip ci]"
-            git pull --rebase origin master
-            git push origin HEAD:master
+            echo "No manifest changes."
+            exit 0
           fi
+
+          git commit -m "ci: update bankapp image to ${{ steps.tag.outputs.sha_short }} [skip ci]"
+
+          git pull --rebase origin master || {
+            echo "Rebase failed because another workflow already updated the manifest."
+            git rebase --abort || true
+            exit 0
+          }
+
+          git push origin HEAD:master
